// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPHbRYqF7NQrwPxcHR3wCAys2qs0cj1zE',
    appId: '1:914930062031:web:961b4e6af4f1aa2cbe9dba',
    messagingSenderId: '914930062031',
    projectId: 'actividad1elena',
    authDomain: 'actividad1elena.firebaseapp.com',
    storageBucket: 'actividad1elena.appspot.com',
    measurementId: 'G-WWGLE6QYJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi5o6Jqw2aROsAXAxLX-mXzH0riNqTkzg',
    appId: '1:914930062031:android:58add40320dbb2cfbe9dba',
    messagingSenderId: '914930062031',
    projectId: 'actividad1elena',
    storageBucket: 'actividad1elena.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCIIax-xPKo2KX5BKyr9UeSvQxnWJsyS8',
    appId: '1:914930062031:ios:6a967b6078d9454fbe9dba',
    messagingSenderId: '914930062031',
    projectId: 'actividad1elena',
    storageBucket: 'actividad1elena.appspot.com',
    iosBundleId: 'practica1.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCIIax-xPKo2KX5BKyr9UeSvQxnWJsyS8',
    appId: '1:914930062031:ios:ae0fc30836f127eabe9dba',
    messagingSenderId: '914930062031',
    projectId: 'actividad1elena',
    storageBucket: 'actividad1elena.appspot.com',
    iosBundleId: 'practica1.example.app.RunnerTests',
  );
}
